game/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.lobby, name='lobby'),
    path('rules/', views.rules, name='rules'),
    path('game/<int:pk>/', views.game, name='game'),
    path('game/create/', views.create_game, name='create_game'),
    path('game/join/<int:pk>/', views.join_game, name='join_game'),
    path('game/<int:pk>/getboard', views.get_game_board, name='get_gameboard'),
    path('game/<int:pk>/getstate', views.get_game_state, name='get_gamestate'),
    ]

game/models.py
from django.db import models

from django.contrib.auth import get_user_model

from datetime import datetime

from .game_logic import GameRun

import django.dispatch

import redis

from django.conf import settings

game_started_signal = django.dispatch.Signal()

def get_deleted_user():
    return get_user_model().objects.get_or_create(username='deleted')[0]

def get_anonymous_user():
    return get_user_model().objects.get_or_create(username='anonymous')[0]

class Game(models.Model):
    creator = models.ForeignKey(get_user_model(),
                                on_delete=models.SET(get_deleted_user),
                                related_name='creator')
    
    players = models.ManyToManyField(get_user_model(),
                                     through='Player')

    winner = models.ForeignKey(get_user_model(),
                               on_delete=models.SET(get_deleted_user),
                               related_name='winner',
                               null=True,
                               blank=True
                               )
    # dates
    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(null=True, blank=True)
    completed = models.DateTimeField(null=True, blank=True)
    modified = models.DateTimeField(auto_now=True)

    finalGameState = models.BinaryField(null=True, blank=True)

    class Meta:
        get_latest_by = "modified"
        ordering = ["-modified"]

    def __str__(self):
        return 'Game #{0}'.format(self.pk)

    @staticmethod
    def get_total_number_of_games():
        return Game.objects.count()
    
    @staticmethod
    def get_open_games():
        return Game.objects.filter(started=None, completed=None)

    @staticmethod
    def get_open_games_not_joined_by_user(user):
        return filter(lambda x: not x.is_user_a_player(user), Game.get_open_games())
 
    @staticmethod
    def created_count(user):
        return Game.objects.filter(creator=user).count()
 
    @staticmethod
    def get_games_for_player(user):
        if not user.is_authenticated:
            return []
        from django.db.models import Q
        return Game.objects.filter(Q(players=user) & Q(completed=None))
 
    @staticmethod
    def get_by_id(id):
        try:
            return Game.objects.get(pk=id)
        except Game.DoesNotExist:
            pass
        
    @staticmethod
    def create_new(user):
        """
        Create a new game
        :param user: the user that created the game
        :return: a new game object
        """
        if not user.is_authenticated:
            user = get_anonymous_user()
        new_game = Game.objects.create(creator=user)
        new_player = Player(user=user, game=new_game, color=0)
        new_player.save()
        return new_game

    def player_join(self, user):
        if not user.is_authenticated:
            user = get_anonymous_user()
        new_player = Player(user=user, game=self, color=self.get_player_count())
        new_player.save()
        return new_player

    def get_player_count(self):
        return self.players.all().count()

    def is_user_a_player(self, user):
        return user in self.players.all()

    def start(self):
        self.running_game = GameRun(self)
        self.mark_started()
        self.running_game.start()
    
    def mark_started(self):
        """
        Marks a game as having started
        """
        self.started = datetime.now()
        self.save() 
        game_started_signal.send(sender=Game.__class__,
                                 game=self,
                                 starting_chips=self.running_game.starting_chips)

    def mark_complete(self, winner):
        """
        Sets a game to completed status and records the winner
        """
        if settings.REDIS_UNIX:
            r = redis.Redis(unix_socket_path=settings.REDIS_UNIX_PATH, db=0)
        else:
            r = redis.Redis(host=settings.REDIS_HOST, port=6379, db=0)
            
        p = r.pipeline()
        key = 'game_' + str(self.pk)
        p.watch(key)
        self.finalGameState = p.get(key)
        p.multi()
        p.delete('game_' + str(self.pk))
        p.execute()
        
        for p in self.players.all():
            if p.username == winner.playername:
                self.winner = p
                break
        self.completed = datetime.now()
        self.save()

class Player(models.Model):
    user = models.ForeignKey(get_user_model(),
                             on_delete=models.SET(get_deleted_user),
                             null=True,
                             blank=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    color = models.IntegerField(default=0, unique=False)

    # if we allow anonymous users, we should not make this uniqueness constraint!
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'game'],
                                    name='unique_players_in_game')
        ]

game/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import HttpRequest, HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator

import os

from .models import Player, Game
from config.utils import get_base_template
from game.utils import get_game_through_redis
from game.game_logic import GameState, GameRun

from django.conf import settings

@never_cache
def lobby(request: HttpRequest) -> HttpResponse:
    user = request.user

    open_games =  list(Game.get_open_games_not_joined_by_user(user))
    og_page_num = request.GET.get("og_page", "1")
    og_paginator = Paginator(object_list=open_games, per_page=15)
    og_page = og_paginator.get_page(og_page_num)

    player_games =  list(Game.get_games_for_player(user))
    pg_page_num = request.GET.get("pg_page", "1")
    pg_paginator = Paginator(object_list=player_games, per_page=15)
    pg_page = pg_paginator.get_page(pg_page_num)
    
    return render(
        request,
        "game/lobby.html",
        {
            "base_template": get_base_template(request),
            "open_games": og_page,
            "player_games": pg_page,
            "total_games": Game.get_total_number_of_games(),
        },
    )


def rules(request:HttpRequest) -> HttpResponse:
    markdown_rules = open(os.path.join(settings.BASE_DIR, "rules.md")).read()
    return render(
            request,
                "game/rules.html",
                { 
                    "base_template": get_base_template(request),
                    "markdown_rules": markdown_rules,
                },
        )

    
@never_cache
def game(request: HttpRequest, pk) -> HttpResponse:
    return render(
        request,
        "game/game.html",
        { 
            "base_template": get_base_template(request),
            "game": Game.get_by_id(pk),
        },
   )

@never_cache
def get_game_board(request: HttpRequest, pk) -> HttpResponse:
    if not request.htmx:
        return game(request, pk)
    else:
        game = Game.get_by_id(pk)
        if game.started == None:
            return render(
            request,
                "game/game_board.html",
                { 
                    "base_template": get_base_template(request),
                    "game": game,
                },
        ) 
        else:
            gameRun = get_game_through_redis(pk)
            enum_dict = {d.name: str(d.value) for d in GameState}
            return render(
                request,
                "game/game_board_running.html",
                { 
                    "base_template": get_base_template(request),
                    "gameRun": gameRun,
                    "game_states": enum_dict,
                },
            ) 

@never_cache
def get_game_state(request: HttpRequest, pk) -> HttpResponse:
    if not request.htmx:
        return HttpResponse(status=204)
    else:
        game = Game.get_by_id(pk)
        if game.started == None:
            return HttpResponse(status=204)
        else:
            available_player_targets = None
            captured_pile = None
            captured_pile_num = None
            winner = None
        
            gameRun = get_game_through_redis(pk)
            enum_dict = {d.name: str(d.value) for d in GameState}
            state = gameRun.state
            if state == GameState.AWAIT_GIVE_MOVE:
                available_colors = GameRun.possible_moves(
                    gameRun.get_living_colors(),
                    gameRun.playing_area[gameRun.last_played_pile]
                )
                available_player_targets = [gameRun.players[p] for p in available_colors]
            elif state == GameState.AWAIT_CHOOSE_KILL:
                captured_pile = gameRun.playing_area[gameRun.last_played_pile]
                captured_pile_num = gameRun.last_played_pile
            elif state == GameState.FINISHED:
                winner = gameRun.winner
                
            return render(
                request,
                "game/game_state_running.html",
                { 
                    "base_template": get_base_template(request),
                    "game": gameRun.db_game,
                    "game_states": enum_dict,
                    "current_player": gameRun.current_player,
                    "state": str(gameRun.state.value),
                    "available_player_targets": available_player_targets,
                    "captured_pile_num": captured_pile_num,
                    "captured_pile": captured_pile,
                    "winner": winner,
                    "alive": [str(p) for p in gameRun.get_living_players()]
                },
            ) 
        

@never_cache
@require_POST
def create_game(request: HttpRequest) -> HttpResponse:
    new_game = Game.create_new(request.user)
    response =  render(
        request,
        "game/game.html",
        {
            "base_template": get_base_template(request),
            "game": new_game,
        },
   )

    response['HX-Push'] = reverse('game', kwargs={'pk': new_game.pk})
    return response

@never_cache
@require_POST
def join_game(request: HttpRequest, pk) -> HttpResponse:
    game = Game.get_by_id(pk)
    game.player_join(request.user)
    
    return render(
        request,
        "game/game.html",
        {
            "base_template": get_base_template(request),
            "game": game,
        },
   ) 

templates/game/events/game_joined_notification.html
<div class="popup" _="on load wait 500ms then transition my opacity to 0 over 400ms then remove me">
  <em>{{ joined_player }}</em> just joined!
</div>

templates/game/events/ingame_entire_pile_killed.html
<td class="chips_list" hx-swap-oob="outerHTML:#pile_{{captured_pile_num}}"
    _="install Put_Down_Pile" id="pile_{{captured_pile_num}}">
  <form ws-send hx-trigger= "chip_put_down"
        hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:{{captured_pile_num}},game:{{game.pk}}}">
  </form>
  <div _="on load call htmx.process('#pile_tr_{{captured_pile_num}}')"></div>
</td>

templates/game/events/ingame_game_started.html
<div hx-swap-oob="outerHTML:#game_started_status">
  {% include "game/game_started_state.html" %}
</div>

templates/game/events/ingame_move_remove.html
<div hx-swap-oob="afterbegin:#possession_{{acting_player}}">
  <span _="on load get the next <div[data-color='{{ used_color }}']/> then transition its opacity to 0 then remove it then remove me"></span>
</div>

templates/game/events/ingame_pile_captured.html
<td hx-swap-oob="outerHTML:#pile_{{captured_pile_num}}" id="pile_{{captured_pile_num}}" class="chips_list" _="install Put_Down_Pile">
  <form ws-send hx-trigger= "chip_put_down"
        hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:{{captured_pile_num}},game:{{game.pk}}}">
  </form>
  <script type="text/hyperscript">
   behavior KillableFromPile
   on click
   if $can_kill_from_pile == true
   trigger chip_killed_from_pile
   remove <#pile_{{captured_pile_num}} .chip/>
   set $can_kill_from_pile to false
   set $can_play to true
   set $active_chip to false
   call htmx.process('#playing_area')
   end
   end
   end
  </script>

  {% for c in captured_pile %}
    <div class="chip killable" data-color="{{ c }}"
         ws-send hx-trigger="chip_killed_from_pile"
         _="install KillableFromPile"
         hx-vals='{"action": "kill_from_capture", "chipColor": "{{c}}","game": "{{game.pk}}"}'>
    </div>
  {% endfor %}
  
  <div _="on load set $can_kill_from_pile to true then set $can_play to false then call htmx.process('#pile_tr_{{captured_pile_num}}')"></div>
</td>

templates/game/events/ingame_pile_captured_others.html
<td hx-swap-oob="outerHTML:#pile_{{captured_pile_num}}" id="pile_{{captured_pile_num}}" class="chips_list" _="install Put_Down_Pile">
  <form ws-send hx-trigger= "chip_put_down"
        hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:{{captured_pile_num}},game:{{game.pk}}}">
  </form>
  {% for c in captured_pile %}
    <div class="chip killable" data-color="{{ c }}">
    </div>
  {% endfor %}
</td>

templates/game/events/ingame_pile_captured_taken.html
<div hx-swap-oob="beforeend:#possession_{{acting_player}}">
  {% for i in captured_pile_one_removed %}
    <div class="chip {% if user == acting_player %}
                clickable" _="install Pickupable(color: {{ i }})
    {% endif %}" data-color="{{ i }}"></div>
  {% endfor %}
</div>

templates/game/events/ingame_pile_created.html
<tr class="pile" id="pile_tr_{{target}}" hx-swap-oob="outerHTML:#next_pile">
  <td _="on load call htmx.process('#pile_tr_{{target}}') then make a <tr #next_pile/> then put it at the end of #playing_area">
    Pile {{ target|add:1 }}:
  </td>
  <td id="pile_{{target}}" class="chips_list"
      _="install Put_Down_Pile"
      ws-send hx-trigger="chip_put_down"
      hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:{{ target }},game:{{game.pk}}}">
  </td>
</tr>

templates/game/events/ingame_pile_killed.html
<td class="chips_list" hx-swap-oob="outerHTML:#pile_{{captured_pile_num}}"
    _="install Put_Down_Pile" id="pile_{{captured_pile_num}}">
  <form ws-send hx-trigger= "chip_put_down"
        hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:{{captured_pile_num}},game:{{game.pk}}}">
  </form>
  <div _="on load call htmx.process('#pile_tr_{{captured_pile_num}}')"></div>
</td>

templates/game/events/ingame_player_killed.html
<div hx-swap-oob="innerHTML:#possession_{{acting_player}}">
  ☠
  <div _="on load add .killed to #possession_{{acting_player}}"></div>
</div>

templates/game/events/ingame_starting_chips.html
{% load custom_filters %}
<div hx-swap-oob="innerHTML:#game_board">
  <div><table id="possessions">
    <caption>Possessions</caption>

    {% for p in game.player_set.all %}
      <tr class="player_possession {% if user == p.user %} this_players_possessions{% endif %}" data-player="{{ p.user.username }}" data-color="{{ p.color }}">
        <td class="playername" >{{ p.user.username }}:</td>
        <td class="chips_list"
            id="possession_{{p.user}}"
            {% if user != p.user %} _="install Put_Down_Possessions" {% endif %}
            ws-send hx-trigger="chip_put_down"
            hx-vals="js:{action:'chip_transfer',chipColor:$active_chip.getAttribute('data-color'),targetPlayer:'{{p.user.username}}',game:{{game.pk}}}">
          
          {% for i in starting_chips|times %}
            {% if user == p.user %}
              <span _="init set $my_color to {{ p.color }}"></span>
            {% endif %}
            <div class="chip
                        {% if user == p.user %}
                        clickable" _="install Pickupable(color: {{p.color}})
                        {% endif %}
                        " data-color="{{ p.color }}"></div>
          {% endfor %}
        </td>
      </tr>
    {% endfor %}

  </table></div>

  <div><table>
    <caption>Playing Area</caption>

    <tbody id="playing_area">
      <tr class="pile" id="pile_tr_0">
        <td>Pile 1:</td>
        <td id="pile_0" class="chips_list"
            _="install Put_Down_Pile"
            ws-send hx-trigger="chip_put_down"
            hx-vals="js:{action:'chip_put',chipColor:$active_chip.getAttribute('data-color'),targetPile:0,game:{{game.pk}}}">
        </td>
      </tr>
      <tr id="next_pile"><td></td></tr>
    </tbody>
  </table></div>

  <div>  <table>
    <caption>Dead Box</caption>
    <tbody  id="dead_box">
      <tr  _="install Put_Down_Possessions"
           ws-send hx-trigger="chip_put_down"
           hx-vals="js:{action:'prisoner_killed_directly',chipColor:$active_chip.getAttribute('data-color'),targetPlayer: '',game:{{game.pk}}}"><td id="dead_box_contents" ></td></tr>
    </tbody>
  </table></div>

</div>

templates/game/events/ingame_state_changed.html
{% load custom_filters %}
<div hx-swap-oob="outerHTML:#game_state"
     id="game_state"
     _="init set $can_play to
                  {% if current_player == user.username and state == game_states|dict_key:'AWAIT_MOVE' %}
                  true
                  {% else %}
                  false
                  {% endif %}
                  then show #messagebox_container
                  ">

  {% if state == game_states|dict_key:'AWAIT_MOVE' %}

    <div>Waiting for a move by <em>{{ current_player }}</em>!</div>

  {% elif state == game_states|dict_key:'AWAIT_GIVE_MOVE' %}

    <div>Please decide who gets the move, <em>{{ current_player }}</em>!</div>

    {% if user.username == current_player %}
      <form ws-send hx-trigger="giveMoveClicked"
            hx-vals='{"action": "give_move", "game": "{{ game.pk }}"}'>
        <select name="move_given">
          {% for p in available_player_targets %}
            <option>{{ p }}</option>
          {% endfor %}
        </select>
          <button type="button" _="on click send giveMoveClicked">Give Move</button>
      </form>
    {% endif %}

  {% elif state == game_states|dict_key:'AWAIT_CHOOSE_KILL' %}

    <div><em>{{ current_player }}</em> has to decide which chip to kill out of the captured pile.</div>

  {% elif state == game_states|dict_key:'AWAIT_REFUSALS' %}

    <div>Will anybody save <em>{{ current_player }}</em>? Please transfer a chip or state your refusal.</div>
    {% if user.username != current_player and user.username in alive %}
      <form ws-send hx-trigger="refuseHelpClicked"
            hx-vals='{"action": "refuse_help", "game": "{{ game.pk }}"}'>
        <button type="button" style="background-color: var(--danger-text-background-color); color:var(--text-color)" _="on click send refuseHelpClicked then set { disabled: true} on me then set my.innerText to 'Help refused!'">Refuse help</button>
      </form>
    {% endif %}

  {% elif state == game_states|dict_key:'FINISHED' %}

    <div>Game finished! <em>{{ winner }}</em> won!</div>

  {% elif state == game_states|dict_key:'ABORTED' %}

    <div>Game aborted.</div>

  {% elif state == game_states|dict_key:'NOT_RUNNING' %}

    <div>Game not running.</div>

  {% endif %}


</div>

templates/game/events/ingame_transfer.html
{% load custom_filters %}
<div hx-swap-oob="beforeend:#possession_{{target}}">
  <div class="chip
              {% if user == target %}
              clickable"  _="install Pickupable(color:{{ used_color }})"
       style="opacity: 0;
              {% endif %}"
       data-color="{{ used_color }}"
  ></div>
</div>

templates/game/events/ingame_transfer_remove.html
<div hx-swap-oob="afterbegin:#possession_{{acting_player}}">
  <span _="on load get the next <div[data-color='{{ used_color }}']/> then transition its opacity to 0 then remove it then remove me"></span>
</div>